export const accountList = [
  { key: 111, account_number: 111, account_type: "N", title: "Tiền mặt" },
  { key: 1111, account_number: 1111, account_type: "N", title: "Tiền Việt Nam" },
  { key: 112, account_number: 112, account_type: "N", title: "Tiền gửi ngân hàng" },
  { key: 1121, account_number: 1121, account_type: "N", title: "Tiền Việt Nam" },
  { key: 1122, account_number: 1122, account_type: "N", title: "Ngoại tệ" },
  { key: 121, account_number: 121, account_type: "N", title: "Chứng khoán kinh doanh" },
  { key: 1211, account_number: 1211, account_type: "N", title: "Cổ phiếu" },
  { key: 1212, account_number: 1212, account_type: "N", title: "Trái phiếu" },
  { key: 128, account_number: 128, account_type: "N", title: "Đầu tư ngắn hạn khác" },
  { key: 1281, account_number: 1281, account_type: "N", title: "Tiền gửi có kỳ hạn" },
  { key: 1288, account_number: 1288, account_type: "N", title: "Các khoản đầu tư khác nắm giữ đến ngày đáo hạn" },
  { key: 131, account_number: 131, account_type: "N", title: "Phải thu khách hàng" },
  { key: 1331, account_number: 1331, account_type: "N", title: "Thuế GTGT được khấu trừ" },
  { key: 136, account_number: 136, account_type: "N", title: "Phải thu nội bộ" },
  { key: 1361, account_number: 1361, account_type: "N", title: "Vốn kinh ở các đơn vị trực thuộc" },
  { key: 1368, account_number: 1368, account_type: "N", title: "Phải thu nội bộ khác" },
  { key: 138, account_number: 138, account_type: "N", title: "Các khoản phải thu khác" },
  { key: 1381, account_number: 1381, account_type: "N", title: "Tài sản thiếu chờ xử lý" },
  { key: 1386, account_number: 1386, account_type: "N", title: "Cầm cố, thế chấp, ký quỹ, ký cược" },
  { key: 1388, account_number: 1388, account_type: "N", title: "Phải thu khác" },
  { key: 141, account_number: 141, account_type: "N", title: "Tạm ứng" },
  { key: 144, account_number: 144, account_type: "N", title: "Các khoản cầm cố, ký cược, ký quỹ ngắn hạn" },
  { key: 151, account_number: 151, account_type: "N", title: "Hàng mua đang đi trên đường" },
  { key: 152, account_number: 152, account_type: "N", title: "Nguyên vật liệu" },
  { key: 153, account_number: 153, account_type: "N", title: "Công cụ, dụng cụ trong kho" },
  { key: 154, account_number: 154, account_type: "N", title: "Chi phí sản xuất kinh doanh dở dang" },
  { key: 155, account_number: 155, account_type: "N", title: "Thành Phẩm" },
  { key: 156, account_number: 156, account_type: "N", title: "Hàng hóa" },
  { key: 157, account_number: 157, account_type: "N", title: "Hàng gửi đi bán" },
  { key: 211, account_number: 211, account_type: "N", title: "Tài sản cố định" },
  { key: 2111, account_number: 2111, account_type: "N", title: "TSCĐ hữu hình" },
  { key: 2112, account_number: 2112, account_type: "N", title: "TSCĐ thuê tài chính" },
  { key: 2113, account_number: 2113, account_type: "N", title: "TSCĐ vô hình" },
  { key: 214, account_number: 214, account_type: "C", title: "Hao mòn TSCĐ" },
  { key: 2141, account_number: 2141, account_type: "C", title: "Hao mòn của TSCĐ hữu hình" },
  { key: 2142, account_number: 2142, account_type: "C", title: "Hao mòn của TSCĐ thuê tài chính" },
  { key: 2143, account_number: 2143, account_type: "C", title: "Hao mòn TSCĐ vô hình" },
  { key: 2147, account_number: 2147, account_type: "C", title: "Hao mòn bất động sản đầu tư" },
  { key: 228, account_number: 228, account_type: "N", title: "Đầu tư góp vốn vào đơn vị khác" },
  { key: 2281, account_number: 2281, account_type: "N", title: "Đầu tư vào công ty liên doanh, liên kết" },
  { key: 2288, account_number: 2288, account_type: "N", title: "Đầu tư khác" },
  { key: 229, account_number: 229, account_type: "N", title: "Dự phòng tổn thất tài sản" },
  { key: 2291, account_number: 2291, account_type: "N", title: "DP giảm giá chứng khoán kinh doanh" },
  { key: 2292, account_number: 2292, account_type: "N", title: "DP tổn thất đầu tư vào đơn vị khác" },
  { key: 2293, account_number: 2293, account_type: "N", title: "DP phải thu khó đòi" },
  { key: 2294, account_number: 2294, account_type: "N", title: "DP giảm giá hàng tồn kho" },
  { key: 241, account_number: 241, account_type: "N", title: "Xây dựng cơ bản dở dang" },
  { key: 2411, account_number: 2411, account_type: "N", title: "Mua sắm tài sản cố định" },
  { key: 2412, account_number: 2412, account_type: "N", title: "Xây dựng cơ bản" },
  { key: 2413, account_number: 2413, account_type: "N", title: "Sửa chữa lớn tài sản cố định" },
  { key: 242, account_number: 242, account_type: "N", title: "Chi phí trả trước" },
  { key: 331, account_number: 331, account_type: "C", title: "Phải trả người bán" },
  { key: 333, account_number: 333, account_type: "C", title: "Thuế và các khoản phải nộp cho Nhà nước" },
  { key: 3331, account_number: 3331, account_type: "C", title: "Thuế GTGT phải nộp" },
  { key: 33311, account_number: 33311, account_type: "C", title: "Thuế giá trị gia tăng đầu ra" },
  { key: 33312, account_number: 33312, account_type: "C", title: "Thuế giá trị gia tăng hàng nhập khẩu" },
  { key: 3332, account_number: 3332, account_type: "C", title: "Thuế tiêu thụ đặc biệt" },
  { key: 3333, account_number: 3333, account_type: "C", title: "Thuế xuất, nhập khẩu" },
  { key: 3334, account_number: 3334, account_type: "C", title: "Thuế TNDN" },
  { key: 3335, account_number: 3335, account_type: "C", title: "Thuế TNCN" },
  { key: 3336, account_number: 3336, account_type: "C", title: "Thuế tài nguyên" },
  { key: 3337, account_number: 3337, account_type: "C", title: "Thuế nhà đất, tiền thuê đất" },
  { key: 3338, account_number: 3338, account_type: "C", title: "Thuế bảo vệ môi trường và các loại thuế khác" },
  { key: 33381, account_number: 33381, account_type: "C", title: "Thuế bảo vệ môi trường" },
  { key: 33382, account_number: 33382, account_type: "C", title: "Các loại thuế khác" },
  { key: 3339, account_number: 3339, account_type: "C", title: "Phí, lệ phí và các khoản phải nộp khác" },
  { key: 334, account_number: 334, account_type: "C", title: "Phải trả người lao động" },
  { key: 335, account_number: 335, account_type: "C", title: "Chi phí phải trả" },
  { key: 336, account_number: 336, account_type: "C", title: "Phải trả nội bộ" },
  { key: 3361, account_number: 3361, account_type: "C", title: "Phải trả nội bộ về vốn kinh doanh" },
  { key: 3368, account_number: 3368, account_type: "C", title: "Phải trả nội bộ khác" },
  { key: 338, account_number: 338, account_type: "C", title: "Phải trả, phải nộp khác" },
  { key: 3381, account_number: 3381, account_type: "C", title: "Tài sản thừa chờ giải quyết" },
];
